apiVersion: v1
name: ecrpublic-chart
description: A Helm chart for the ACK service controller for Amazon Elastic Container Registry Public (ECR Public)
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/aws-controllers-k8s/ecrpublic-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/ecrpublic-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: ECR Public Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ecrpublic-maintainer
keywords:
  - aws
  - kubernetes
  - ecrpublic
